Bump einaregilsson/build-number to v3 as set-env was deprecated in GitHub Actions (#1199)
* Bump einaregilsson/build-number to v3 as set-env was deprecated in GitHub Actions

```
Error: Unable to process command '::set-env name=BUILD_NUMBER::20201118053615' successfully.
8
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

* Empty commit to trigger GitHub Actions

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>